SHELL = /bin/sh

SCIDIR=../../..
SCIDIR1=..\..\..

include $(SCIDIR)/Makefile.incl

.SUFFIXES: .sci .bin $(SUFFIXES)

NAME =metalib
NAM =SCI/contrib/cs5/macros

MACROS= affec.sci \
	bilevel_macros.sci \
	dsdold.sci \
	dsdtest.sci \
	formatman.sci \
	glstotal_spr.sci \
	net_macros.sci \
	traffic_macros.sci \
	translate.sci

include $(SCIDIR)/macros/Make.lib
